### ISSUE TITLE
Fixed to n Characters, or can be more?

### ISSUE THREAD

**Issue by afahmiparidin** [peterberbec/yourls-keyword_charset_length#3]
Dear @peterberbec,

![image](https://user-images.githubusercontent.com/5966211/38548616-c4411d86-3ce4-11e8-8a95-ec00cf365357.png)

when we set the value of character is 6, does it mean by minimum system will get 6 characters keyword? or limit to only 6 characters keyword? 

Thank you.
**Fahmi Paridin**

**Comment by peterberbec** [comment]
I believe this sets it to 6 fixed length. I've never run out even with 6.

**Comment by peterberbec** [comment]
Oh, I get what you mean! 6 is for randomly generated. You can manually
change the link to any length

**Comment by afahmiparidin** [comment]
Hi @peterberbec ,

actually im looking for URL randomize solution that
1. minimum character is 6
2. generate random unique URL

however, i've found the solution and wrote a plugin about it. will share it soon 👍 

Thank you.
**Fahmi Paridin**

**Comment by peterberbec** [comment]
Great! Best thing about yourls is the expandability!

**Comment by afahmiparidin** [comment]
Dear @peterberbec ,

This is my plugin. 👍 using Hashids as the hashing engine, and uses next_id as counter and make it unique everytime a new link is generated.

[https://github.com/afahmiparidin/Hashids-Yourls/](https://github.com/afahmiparidin/Hashids-Yourls/)
